category:
    Tercera: 153.38
    Liga-Nacional-Juvenil: 42.02

expenses:
    minium: 15
    medium: 30
    maximum: 45

expensesTravel:
  Tercera:
    Salamanca: 100
    Astorga: 150
    La-Bañeza: 180
    Tordesillas: 50
    Palencia:
    Zamora:
    Soria:
    Avila:
    Aranda-de-Duero:
    Cebreros:
    Virgen-del-Camino:
    Burgos:
    Bembibre:
    Almazán:
    Burgo-de-Osma:
    





