category:
    Tercera: 153.38
    Liga-Nacional-Juvenil: 42.02

expenses:
    minium: 15
    medium: 30
    maximum: 45

localTeam:
  tercera:
    Salamanca: 100
    Astorga: 150
    La-Bañeza: 180
    Tordesillas: 50
    Palencia:
    Zamora:
    Soria:
    Avila:
    Aranda-de-Duero:
    Cebreros:
    Virgen-del-Camino:
    Burgos:
    Bembibre:
    Almazán:
    Burgo-de-Osma:
    
# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

# Connection url for the database "mysql"
spring:
  datasource:
    url : jdbc:mysql://127.0.0.1:33061/mysql
    username: root
    password: appoint
    testWhileIdle: true
    validationQuery: SELECT 1




