category:
    Tercera: 153.38
    Liga-Nacional-Juvenil: 42.02

expenses:
    mini: 15
    medium: 30
    max: 45

expensesTravel:
  Tercera:
    Salamanca:
    Astorga:
    La-Bañeza:
    Tordesillas:
    Palencia:
    Zamora:
    Soria:
    Avila:
    Aranda-de-Duero:
    Cebreros:
    Virgen-del-Camino:
    Burgos:
    Bembibre:
    Almazán:
    Burgo-de-Osma:
    





